---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: spring-openshift
    provider: fabric8
    version: 0.0.1-SNAPSHOT
    group: com.example.openshift
  name: my-database-secret
stringData:
  user: luke
  password: secret
